title: "HERMES-WIRE: Step1 pipeline"
subtitle: ""
intro_text: False

report_header_info:
    - Please cite: "Manuscript in progress"

extra_fn_clean_trim: 
    - '_2P'
    - '_1P'
    - '.aln'

thousandsSep_format: ","
read_count_multiplier: 0.001
read_count_prefix: 'K'
read_count_desc: 'thousands'


module_order:

 - fastqc:
        name: 'FastQC (raw)'
        path_filters:
            - '*_fastqc.zip'
        path_filters_exclude:
            - '*_*P_fastqc.zip'
 - trimmomatic
 - fastqc:
        name: 'FastQC (trimmed)'
        info: 'This section of the report shows FastQC results after adapter trimming.'
        path_filters:
            - '*_*P_fastqc.zip'
 - bowtie2